# Generated by Django 3.2.4 on 2021-06-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablity',
            options={'get_latest_by': 'date_created'},
        ),
    ]
