# Generated by Django 3.2.3 on 2021-05-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_available_recurrence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Available',
            new_name='Availablity',
        ),
    ]
