# Generated by Django 3.2.3 on 2021-05-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsprofiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
