# Generated by Django 3.2.3 on 2021-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsprofiles', '0003_patientprofile_blood_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
