# Generated by Django 3.2.4 on 2021-06-04 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='date',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
