# Generated by Django 3.2.3 on 2021-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_date_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='from_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='to_time',
            field=models.DateField(null=True),
        ),
    ]
