# Generated by Django 3.2.3 on 2021-05-31 08:35

import Myclasses
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='recurrence',
            field=Myclasses.Rec(blank=True, choices=[('0 G day', 'Every day.'), ('0 month', 'Every month.'), ('0 year', 'Every year.'), ('1 sunday', 'Every sunday.'), ('1 monday', 'Every monday.'), ('1 tuesday', 'Every tuesday.'), ('1 wednesday', 'Every wednesday.'), ('1 thursday', 'Every thursday.'), ('1 friday', 'Every friday.'), ('1 saturday', 'Every saturday.')], max_length=93, null=True),
        ),
    ]
