# Generated by Django 3.2.3 on 2021-05-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20210529_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='importance',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('averge', 'averge'), ('heigh', 'heigh')], max_length=50),
        ),
    ]
