# Generated by Django 3.2.3 on 2021-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_date_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
