# Generated by Django 3.2.4 on 2021-06-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('obj_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('field_value', models.CharField(max_length=500)),
                ('action', models.CharField(blank=True, choices=[('added', 'added'), ('changed', 'changed'), ('deleted', 'deleted')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='timesheets.column')),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
    ]
