# Generated by Django 3.2.4 on 2021-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('added', 'added'), ('changed', 'changed'), ('deleted', 'deleted')], max_length=50)),
                ('model_target', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, max_length=50, null=True)),
                ('field_target', models.CharField(blank=True, max_length=50)),
                ('field_value', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
