# Generated by Django 3.2.3 on 2021-05-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DalyPlanTracker',
            fields=[
                ('changetrack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timesheets.changetrack')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('timesheets.changetrack',),
        ),
        migrations.CreateModel(
            name='PatientProfileTracker',
            fields=[
                ('changetrack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timesheets.changetrack')),
                ('prescriptions', models.TextField(blank=True, max_length=999, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('timesheets.changetrack',),
        ),
    ]
