# Generated by Django 3.2.4 on 2021-06-07 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetrack',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changetrack',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changetrack',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='who_can_see_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
