# Generated by Django 3.2.3 on 2021-05-24 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientsprofiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetrack',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofiletracker',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='symptoms_tracker', to='patientsprofiles.PatientProfile'),
        ),
        migrations.AddField(
            model_name='patientprofiletracker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
