# Generated by Django 3.2.3 on 2021-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_changetrack_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetrack',
            name='model_id',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
