# Generated by Django 3.2.4 on 2021-06-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'get_latest_by': 'date_created'},
        ),
    ]
