# Generated by Django 3.2.4 on 2021-06-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_value_obj_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='obj_id',
            new_name='object_id',
        ),
    ]
