# Generated by Django 3.2.3 on 2021-05-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_changetrack_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changetrack',
            old_name='model_id',
            new_name='object_id',
        ),
    ]
