# Generated by Django 3.2.3 on 2021-05-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheets', '0004_rename_model_id_changetrack_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changetrack',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='changetrack',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
