# Generated by Django 3.2.4 on 2021-06-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'date_created'},
        ),
    ]
