# Generated by Django 3.2.3 on 2021-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=999, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('importance', models.CharField(blank=True, choices=[('low', 'low'), ('averge', 'averge'), ('heigh', 'heigh')], max_length=50)),
                ('target_groups', models.ManyToManyField(blank=True, null=True, related_name='Notification_target_groups', to='auth.Group')),
            ],
        ),
    ]
