# Generated by Django 3.2.3 on 2021-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_target_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
