# Generated by Django 3.2.3 on 2021-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_target_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
